### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by Potato-git13** [sdushantha/wifi-password#3]
I like it! But can you please comment the code. That way it is easier to read and understand.

**Comment by sdushantha** [comment]
Happy to hear you liked this script!

I tend to add a lot of comments in my code but I felt that this project did not need many comments because everything seemed straightforward and I felt that it would be redundant. For example, I don't want to do this as the function is pretty straightforward in my opinion:
```python
# Print error message and then exit with a status code 1
def print_error(text):
    print(f"ERROR: {text}")
    sys.exit(1)
```

Let me know what section of the code seems a little confusing and I'll see if it needs comments to better understand the code :)

**Comment by Potato-git13** [comment]
Thanks for the reply. I was a bit confused by this line:
`output, _ = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, shell=True).communicate()`
I know that it runs a command but i don't exactly know what it does.

**Comment by sdushantha** [comment]
In that case, I think it would be best for the reader to check [the documentation  for `subprocess.Popen`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) because I don't want to rewrite the documentation as a comment.

What that code basically does is execute a command in a new process in a shell, where the standard output should be a pipe to the standard stream should be opened and then sending the standard error to `/dev/null` so that errors are not shown. The `.communicate()` part lets us fetch the standard output of the command we executed.
