### ISSUE TITLE
pip install exits successfully on Git Bash, but wifi-password: not recognized

### ISSUE THREAD

**Issue by KevinIsMyName** [sdushantha/wifi-password#33]
> $ wifi-password
> bash: wifi-password: command not found

Not sure why wifi-password command not recognized, I tried reloading Git Bash, but same error.

**But installing through Git worked, so I'm currently using that.**

[output.txt](https://github.com/sdushantha/wifi-password/files/5905754/output.txt)

Attached is a snippet log of my terminal.

I suppose the next issue would be the command returning `ERROR: SSID was not found` regardless of what flags I pass through.

**Comment by sdushantha** [comment]
Hey @KevinIsMyName,

```
Kevin@KEVIN-AMD-PC MINGW64 ~
$ pip install wifi-password
Requirement already satisfied: wifi-password in c:\users\kevin\appdata\roaming\python\python38\site-packages (1.0.7)
Requirement already satisfied: qrcode in c:\users\kevin\appdata\roaming\python\python38\site-packages (from wifi-password) (6.1)
Requirement already satisfied: six in c:\users\kevin\appdata\local\programs\python\python38-32\lib\site-packages (from qrcode->wifi-password) (1.14.0)
Requirement already satisfied: colorama in c:\users\kevin\appdata\roaming\python\python38\site-packages (from qrcode->wifi-password) (0.4.4)

Kevin@KEVIN-AMD-PC MINGW64 ~
$ wifi-password
bash: wifi-password: command not found
```
The reason why this is happening is most likely because the directory which `pip` stores the scripts/commands that you have installed is not in your `$PATH`. I unfortunately don't much about Python's directory structure on Windows, so you'll have to try and Google it.

---

```
Kevin@KEVIN-AMD-PC MINGW64 ~
$ git clone https://github.com/sdushantha/wifi-password
Cloning into 'wifi-password'...
remote: Enumerating objects: 169, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 169 (delta 105), reused 79 (delta 44), pack-reused 0
Receiving objects: 100% (169/169), 14.63 MiB | 13.15 MiB/s, done.
Resolving deltas: 100% (105/105), done.

Kevin@KEVIN-AMD-PC MINGW64 ~
$ cd wifi-password

Kevin@KEVIN-AMD-PC MINGW64 ~/wifi-password (master)
$ python3 setup.py install
bash: /c/Users/Kevin/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
```

There must be something wrong with Python3's permissions on your system since when you ran the same command but with `python` instead, it worked. But like I said earlier, I dont know much about how Python works on Windows.

---

```
Kevin@KEVIN-AMD-PC MINGW64 ~/wifi-password (master)
$ wifi-password
ERROR: SSID was not found
```

Looks like you were able to install `wifi-password`, that's great!
Well, I believe that the error must be occurring because you are using Git Bash. There is a chance that `wifi-password` thinks that you are using Linux and then is trying to execute the code for Linux systems.

---

Could you run the Python code below through Git Bash and let me know what the output is?
```python
import sys
sys.platform
```

**Comment by KevinIsMyName** [comment]
```
Kevin@KEVIN-AMD-PC MINGW64 ~
$ python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'win32'
```

Yep! I was thinking of mentioning that it's probably because it's Git Bash. I wanted to compare it to a WSL2 Ubuntu-20.04 LTS, but that was another rabbithole (that I don't feel like digging because busybusybusy).

I think it might just be best to install it with Git and the setuptools if you're using a non-Linux architecture, like GitHub
