### ISSUE TITLE
Any way to prevent this MacOS prompt?

### ISSUE THREAD

**Issue by joshuaquek** [sdushantha/wifi-password#35]
I understand that Mac will prompt for admin access every time I run `wifi-password` for security purposes. Is there any way to give `wifi-password` admin access always so as to easily access the wifi password?

![image](https://user-images.githubusercontent.com/5335756/106545882-269e7600-6545-11eb-8b95-4f7d9584ef51.png)

I am somewhat satisfied that it does prompt for username and password before fetching the keychain credential. However, it would be more convenient to simply run it and get the wifi password directly haha

**Comment by sdushantha** [comment]
Hey @joshuaquek,

I don't think it is possible to get rid of that prompt. The reason why you are getting prompted is because we are fetching the password from the Keychain. Your username is needed to access the credentials since everything is stored under a user and not the root user.

I too would like to get rid of that prompt but it seems like macOS won't let us do that.

**Comment by joshuaquek** [comment]
ok no worries, thanks!
